import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { HeroHeader } from "@/components/Header";
import FooterSection from "@/components/Footer";
=======
import { Toaster } from "@/components/ui/sonner";
>>>>>>> 5ca9f0a4b1ccca29cfa00a429fac90ba3ef44d16

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <HeroHeader />
        {children}
<<<<<<< HEAD
        <FooterSection />
=======
        <Toaster />
>>>>>>> 5ca9f0a4b1ccca29cfa00a429fac90ba3ef44d16
      </body>
    </html>
  );
}
